version: '3'

services:
  app:
    build: .
    expose:
      - '3000'
    environment:
      - NODE_ENV=production
    env_file:
      - .env

  nginx:
    image: nginx:alpine
    ports:
      - '80:80'
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
